INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('BM34', 'BRUNO MARS', 'HAWAII', '39', 'M');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('WE22', 'THE WEEKND', 'LAS VEGAD', '27', 'M');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('DL21', 'DUA LIPA', 'LONDON', '25', 'F');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('AC07', 'AVICII', 'NEW YORK', '32', 'M');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('LDR08', 'LANA D RAY', 'BOSTON', '31', 'F');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('AD27', 'ADELE', 'CAL', '42', 'F');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('HS65', 'H STYLES', 'INDIANA', '24', 'M');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('ID44', 'I DRAGONS', 'DENVER', '29', 'M');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('AJ37', 'A SINGH', 'MUMBAI', '33', 'M');
INSERT INTO `music_databse`.`artists` (`ARTIST_ID`, `ARTIST_NAME`, `ARTIST_LOCATION`, `ARTIST_AGE`, `ARTIST_GENDER`) VALUES ('KK75', 'KK', 'MUMBAI', '42', 'M');


USE MUSIC_DATABSE;

SELECT * FROM ARTISTS;