CREATE database MUSIC_DATABSE;

USE MUSIC_DATABSE;



CREATE TABLE SONGPLAYS(
SONGPLAY_ID VARCHAR(10),
START_TIME DATE,
USER_ID VARCHAR(10),
SONG_ID VARCHAR(10),
ARTIST_ID VARCHAR(10),
SESSION_ID VARCHAR(10),
LOCATION VARCHAR(50),
PRIMARY KEY(USER_ID),
UNIQUE (START_TIME),
UNIQUE(SONG_ID),
UNIQUE(ARTIST_ID)
);




CREATE TABLE USERS(
USER_ID VARCHAR(10),
FIRST_NAME VARCHAR(10),
LAST_NAME VARCHAR(10),
GENDER VARCHAR(10)
);

ALTER TABLE USERS
ADD FOREIGN KEY (USER_ID) REFERENCES SONGPLAYS(USER_ID);


CREATE TABLE TIIME(
START_TIME DATE,
HOURS BIGINT(10),
DAYS BIGINT(10),
WEEKS BIGINT(10),
MONTHS BIGINT(10),
YEARS BIGINT(10),
WEEKDYAS BIGINT(10)
);



ALTER TABLE TIIME
ADD FOREIGN KEY (START_TIME) REFERENCES SONGPLAYS(START_TIME);



CREATE TABLE SONGS(
SONG_ID VARCHAR(10),
SONG_NAME VARCHAR(10),
ARTIST_ID VARCHAR(10),
YEAR_RELEASE VARCHAR(10),
DURATION_SECS VARCHAR(10)
);

ALTER TABLE SONGS
ADD FOREIGN KEY (SONG_ID) REFERENCES SONGPLAYS(SONG_ID);



CREATE TABLE ARTISTS(
ARTIST_ID VARCHAR(10),
ARTIST_NAME VARCHAR(10),
ARTIST_LOCATION VARCHAR(10),
ARTIST_AGE VARCHAR(10),
ARTIST_GENDER VARCHAR(10)
);


ALTER TABLE ARTISTS
ADD FOREIGN KEY (ARTIST_ID) REFERENCES SONGPLAYS(ARTIST_ID);