INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S001', '24K MAGIC', 'BM34', '2016', '232');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S002', 'HEARTLESS', 'WE22', '2021', '239');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S003', 'PHYSICAL', 'DL21', '2020', '187');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S004', 'NIGHTS', 'AC07', '2014', '205');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S005', 'BARTENDER', 'LDR08', '2014', '200');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S006', 'HELLO', 'AD27', '2011', '191');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S007', 'WATERMELON', 'HS65', '2018', '249');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S008', 'BILIEVER', 'ID44', '2016', '250');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S009', 'AASHIQI', 'AJ37', '2015', '246');
INSERT INTO `music_databse`.`songs` (`SONG_ID`, `SONG_NAME`, `ARTIST_ID`, `YEAR_RELEASE`, `DURATION_SECS`) VALUES ('S010', 'DING DONG', 'KK75', '2003', '221');


USE MUSIC_DATABSE;
SELECT * FROM SONGS;